on: [ push, pull_request ]

name: Tests

jobs:
  test:
    name: Tox

    strategy:
      matrix:
        python-version: [ "3.10", "3.9","3.8", "3.7" ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        #os: [ubuntu-latest]
        #python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
        exclude:
          - os: windows-latest
            python-version: pypy3
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'poetry.lock'
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
          parallel: true
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
        parallel-finished: true
